spring.application.name=springboot-mall
server.address=0.0.0.0
server.port=9527
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/mall?serverTimezone=Asia/Taipei&characterEncoding=utf-8
spring.datasource.username=root
spring.datasource.password=aa830830

spring.jackson.time-zone=GMT+8
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

# Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=littleblack0830@gmail.com
spring.mail.password=amacpyyjmluyrrce
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# OpenAI Configuration
spring.ai.openai.apiKey=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
spring.ai.openai.model=gpt-4o
spring.ai.openai.embedding.model=text-embedding-ada-002
spring.ai.openai.temperature=0.7
